
// This file is generated by Firebase Studio.
'use server';

// Importando os novos fluxos do mindFlowAi do novo local
import { 
  askEstrelaMind as askEstrelaMindFlow,
  type MindFlowChatInput, 
  type MindFlowChatOutput,
  searchEstrelaMind as searchEstrelaMindFlow,
  type MindFlowSearchInput,
  type MindFlowSearchOutput
} from '@/app/api/ai/flows/mindFlowAi'; // Caminho atualizado

export async function askEstrelaMind(input: MindFlowChatInput): Promise<MindFlowChatOutput> {
  try {
    console.log("Chamando askEstrelaMindFlow com input:", JSON.stringify(input, null, 2));
    const response = await askEstrelaMindFlow(input);
    console.log("Resposta de askEstrelaMindFlow:", JSON.stringify(response, null, 2));
    return response;
  } catch (error: any) {
    console.error("Erro detalhado ao chamar askEstrelaMindFlow:", error);
    let errorMessage = "Desculpe, encontrei um erro ao processar sua pergunta. Por favor, tente novamente mais tarde.";
    if (error.message) {
      errorMessage += ` Detalhe: ${error.message}`;
    }
    if (error.cause) {
      errorMessage += ` Causa: ${JSON.stringify(error.cause, null, 2)}`;
    }
     if (error.response && error.response.data) {
      errorMessage += ` Resposta da API: ${JSON.stringify(error.response.data, null, 2)}`;
    }
    return { answer: errorMessage };
  }
}

export async function performAiSearch(input: MindFlowSearchInput): Promise<MindFlowSearchOutput> {
  try {
    console.log("Chamando searchEstrelaMindFlow com input:", JSON.stringify(input, null, 2));
    const response = await searchEstrelaMindFlow(input);
    console.log("Resposta de searchEstrelaMindFlow:", JSON.stringify(response, null, 2));
    return response;
  } catch (error: any) {
    console.error("Erro detalhado ao chamar searchEstrelaMindFlow:", error);
    let errorMessage = "Desculpe, não consegui realizar a pesquisa neste momento. Tente novamente.";
     if (error.message) {
      errorMessage += ` Detalhe: ${error.message}`;
    }
    if (error.cause) {
      errorMessage += ` Causa: ${JSON.stringify(error.cause, null, 2)}`;
    }
    if (error.response && error.response.data) {
      errorMessage += ` Resposta da API: ${JSON.stringify(error.response.data, null, 2)}`;
    }
    return { searchResults: errorMessage };
  }
}
    
