
// This file is generated by Firebase Studio.
'use server';

/**
 * @fileOverview Este arquivo define os fluxos de IA para Estrela, a assistente virtual da CEUMA.
 * Inclui funcionalidades para responder a perguntas gerais (chat) e realizar pesquisas específicas
 * sobre o ambiente AVA (Moodle) da Universidade CEUMA.
 *
 * - askEstrelaMind - Função para interações de chat com Estrela.
 * - MindFlowChatInput - Tipo de entrada para askEstrelaMind.
 * - MindFlowChatOutput - Tipo de saída para askEstrelaMind.
 * - searchEstrelaMind - Função para realizar pesquisas com IA através de Estrela.
 * - MindFlowSearchInput - Tipo de entrada para searchEstrelaMind.
 * - MindFlowSearchOutput - Tipo de saída para searchEstrelaMind.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Esquemas para a funcionalidade de Chat
const MindFlowChatInputSchema = z.object({
  question: z.string().describe('A pergunta do estudante para Estrela sobre o uso, funcionalidades, políticas ou recursos do ambiente AVA (Moodle) da Universidade CEUMA.'),
});
export type MindFlowChatInput = z.infer<typeof MindFlowChatInputSchema>;

const MindFlowChatOutputSchema = z.object({
  answer: z.string().describe('A resposta da Estrela AI Assistente para a pergunta do estudante sobre o ambiente AVA (Moodle) da CEUMA.'),
});
export type MindFlowChatOutput = z.infer<typeof MindFlowChatOutputSchema>;

// Esquemas para a funcionalidade de Pesquisa IA
const MindFlowSearchInputSchema = z.object({
  searchQuery: z.string().describe('A consulta de pesquisa do estudante para encontrar informações específicas sobre o ambiente AVA (Moodle) da Universidade CEUMA.'),
});
export type MindFlowSearchInput = z.infer<typeof MindFlowSearchInputSchema>;

const MindFlowSearchOutputSchema = z.object({
  searchResults: z.string().describe('Um resumo conciso dos resultados da pesquisa encontrados pela IA, referentes ao ambiente AVA (Moodle) da Universidade CEUMA, formatados para exibição no chat.'),
});
export type MindFlowSearchOutput = z.infer<typeof MindFlowSearchOutputSchema>;


// Wrapper exportado para a função de chat
export async function askEstrelaMind(input: MindFlowChatInput): Promise<MindFlowChatOutput> {
  return estrelaMindChatFlow(input);
}

// Wrapper exportado para a função de pesquisa
export async function searchEstrelaMind(input: MindFlowSearchInput): Promise<MindFlowSearchOutput> {
  return estrelaMindSearchFlow(input);
}

// Prompt para o Chat com Estrela
const chatPrompt = ai.definePrompt({
  name: 'estrelaMindChatPrompt',
  input: {schema: MindFlowChatInputSchema},
  prompt: `Você é Estrela, uma assistente virtual AI amigável e especialista no Ambiente Virtual de Aprendizagem (AVA/Moodle) da Universidade CEUMA. Sua missão é ajudar os estudantes a navegar e utilizar o AVA/Moodle da CEUMA da forma mais eficiente possível.

Responda exclusivamente a perguntas sobre:
- Como usar as funcionalidades do AVA/Moodle da CEUMA (ex: enviar tarefas, participar de fóruns, acessar notas, encontrar materiais de aula).
- Recursos específicos disponíveis no AVA/Moodle da CEUMA.
- Políticas e diretrizes relacionadas ao uso do AVA/Moodle na CEUMA.
- Dicas e boas práticas para o estudo no AVA/Moodle da CEUMA.

Se uma pergunta for sobre a Universidade CEUMA em geral, mas não especificamente sobre o AVA/Moodle (ex: horários da biblioteca, cursos oferecidos, mensalidades), ou se for completamente fora do escopo da CEUMA (ex: "Qual a capital da França?" ou "Conte uma piada"), informe educadamente que sua especialidade é o ambiente AVA/Moodle da CEUMA e que você pode ajudar com questões relacionadas a ele. Não tente responder perguntas fora do seu escopo de especialização (AVA/Moodle da CEUMA).

Mantenha suas respostas claras, concisas e diretas. Use formatação Markdown quando apropriado (listas, negrito) para melhorar a legibilidade.

Pergunta do estudante: {{{question}}}
`,
});

// Fluxo para o Chat com Estrela
const estrelaMindChatFlow = ai.defineFlow(
  {
    name: 'estrelaMindChatFlow',
    inputSchema: MindFlowChatInputSchema,
    outputSchema: MindFlowChatOutputSchema,
  },
  async (input) => {
    try {
      const response = await chatPrompt(input);
      const answerText =
        (typeof response.text === 'string' ? response.text : '') ||
        (typeof response.output === 'object' &&
        response.output &&
        'answer' in response.output &&
        typeof (response.output as {answer?: string}).answer === 'string'
          ? (response.output as {answer?: string}).answer ?? ''
          : '');

      if (answerText.trim()) {
        return {answer: answerText.trim()};
      }
    } catch (error) {
      console.error('Erro no estrelaMindChatFlow:', error);
    }

    return {
      answer:
        'Tive um problema temporário ao gerar a resposta agora. Tente novamente em alguns segundos com a mesma pergunta sobre o AVA da CEUMA.',
    };
  }
);

// Prompt para a Pesquisa IA com Estrela
const searchPrompt = ai.definePrompt({
  name: 'estrelaMindSearchPrompt',
  input: {schema: MindFlowSearchInputSchema},
  prompt: `Você é Estrela, uma assistente de pesquisa AI para estudantes da Universidade CEUMA, com foco total no ambiente AVA (Moodle). Sua tarefa é processar a consulta de pesquisa fornecida e retornar um resumo conciso e relevante de informações que seriam encontradas nos manuais, FAQs, tutoriais e recursos do ambiente AVA (Moodle) da CEUMA.

Concentre-se em fornecer informações acionáveis ou direcionamentos para onde o estudante pode encontrar mais detalhes DENTRO do AVA/Moodle da CEUMA. A pesquisa é exclusivamente sobre o AVA/Moodle da CEUMA.

Consulta de pesquisa do estudante sobre o AVA/Moodle: {{{searchQuery}}}

Formato da Resposta:
- Forneça um breve parágrafo resumindo os resultados da pesquisa sobre o ambiente AVA da CEUMA.
- Se apropriado, sugira links ou seções específicas do AVA/Moodle da CEUMA (de forma genérica, ex: "Consulte o tutorial 'Como enviar tarefas' na seção de Ajuda do AVA" ou "A funcionalidade de fórum no AVA pode ser útil para isso").
- Use formatação Markdown para clareza (listas, negrito).
- Se a consulta de pesquisa parecer não relacionada ao AVA/Moodle da CEUMA, informe que sua pesquisa é especializada no AVA/Moodle e pergunte se o estudante gostaria de reformular a pesquisa para algo relacionado ao ambiente virtual.
`,
});

// Fluxo para a Pesquisa IA com Estrela
const estrelaMindSearchFlow = ai.defineFlow(
  {
    name: 'estrelaMindSearchFlow',
    inputSchema: MindFlowSearchInputSchema,
    outputSchema: MindFlowSearchOutputSchema,
  },
  async (input) => {
    try {
      const response = await searchPrompt(input);
      const searchText =
        (typeof response.text === 'string' ? response.text : '') ||
        (typeof response.output === 'object' &&
        response.output &&
        'searchResults' in response.output &&
        typeof (response.output as {searchResults?: string}).searchResults === 'string'
          ? (response.output as {searchResults?: string}).searchResults ?? ''
          : '');

      if (searchText.trim()) {
        return {searchResults: searchText.trim()};
      }
    } catch (error) {
      console.error('Erro no estrelaMindSearchFlow:', error);
    }

    return {
      searchResults:
        'Não consegui concluir a pesquisa neste momento. Tente novamente em instantes com outra formulação da sua busca sobre o AVA.',
    };
  }
);

